[phases.setup]
commands = ["npm install -g pnpm"]

[phases.build]
commands = [
  "pnpm install --frozen-lockfile",
  "echo 'Building...'"
]

[phases.start]
commands = [
  "echo 'Starting...'",
  "pnpm run start"
]
