[phases.setup]
commands = [
  "npm install -g pnpm",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
commands = [
  "pnpm install --frozen-lockfile",
  "pnpm run build"
]

[phases.start]
commands = [
  "pnpm run start"
]
